// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace Colos2.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250610221931_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeFirstTemplate.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            FirstName = "John",
                            LastName = "Pork"
                        },
                        new
                        {
                            Id = -2,
                            FirstName = "John",
                            LastName = "Pork"
                        },
                        new
                        {
                            Id = -3,
                            FirstName = "John",
                            LastName = "Smith"
                        });
                });

            modelBuilder.Entity("CodeFirstTemplate.Models.Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FulfilledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("ClientId");

                    b.HasIndex("StatusId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            id = -1,
                            ClientId = -2,
                            CreatedAt = new DateTime(2009, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FulfilledAt = new DateTime(2009, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = -1
                        },
                        new
                        {
                            id = -2,
                            ClientId = -2,
                            CreatedAt = new DateTime(2009, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FulfilledAt = new DateTime(2009, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = -3
                        },
                        new
                        {
                            id = -3,
                            ClientId = -1,
                            CreatedAt = new DateTime(2009, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FulfilledAt = new DateTime(2009, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = -3
                        });
                });

            modelBuilder.Entity("CodeFirstTemplate.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            id = -1,
                            Name = "Apple",
                            Price = 9.9900000000000002
                        },
                        new
                        {
                            id = -2,
                            Name = "Apple",
                            Price = 9.9900000000000002
                        },
                        new
                        {
                            id = -3,
                            Name = "Apple",
                            Price = 9.9900000000000002
                        });
                });

            modelBuilder.Entity("CodeFirstTemplate.Models.Product_Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductOrders");

                    b.HasData(
                        new
                        {
                            id = -1,
                            Amount = 123,
                            OrderId = -1,
                            ProductId = -2
                        },
                        new
                        {
                            id = -2,
                            Amount = 123,
                            OrderId = -3,
                            ProductId = -2
                        },
                        new
                        {
                            id = -3,
                            Amount = 123,
                            OrderId = -1,
                            ProductId = -3
                        });
                });

            modelBuilder.Entity("CodeFirstTemplate.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Name = "New"
                        },
                        new
                        {
                            Id = -2,
                            Name = "New"
                        },
                        new
                        {
                            Id = -3,
                            Name = "New"
                        });
                });

            modelBuilder.Entity("CodeFirstTemplate.Models.Order", b =>
                {
                    b.HasOne("CodeFirstTemplate.Models.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirstTemplate.Models.Status", "Status")
                        .WithMany("Orders")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("CodeFirstTemplate.Models.Product_Order", b =>
                {
                    b.HasOne("CodeFirstTemplate.Models.Order", "Order")
                        .WithMany("ProductOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirstTemplate.Models.Product", "Product")
                        .WithMany("ProductOrders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CodeFirstTemplate.Models.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CodeFirstTemplate.Models.Order", b =>
                {
                    b.Navigation("ProductOrders");
                });

            modelBuilder.Entity("CodeFirstTemplate.Models.Product", b =>
                {
                    b.Navigation("ProductOrders");
                });

            modelBuilder.Entity("CodeFirstTemplate.Models.Status", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
